dopee_website_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DopeeWebsiteBundle:Default:index }

dopee_website_contactform:
    path:      /
    defaults:  { _controller: DopeeWebsiteBundle:Default:contact }

dopee_website_contact_crud:
    resource: "@DopeeWebsiteBundle/Controller/ContactController.php"
    prefix:   /
    type:     annotation
